import { Toaster } from '@/components/ui/sonner';
import AuthProvider from '@/context/AuthProvider';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Mystery Message',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <AuthProvider>
        <body className={inter.className}>
          {children}
          <Toaster
            toastOptions={{
              classNames: {
                error: 'bg-red-400',
                success: 'text-gray-800 bg-green-200',
                warning: 'text-yellow-400',
                info: 'bg-blue-500',
              },
            }}
          />
        </body>
      </AuthProvider>
    </html>
  );
}
